# Generated by Django 3.2.7 on 2021-09-05 10:20

from django.db import migrations, models
import forecasts.utils.unique


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MyGroup', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('guid', models.CharField(default=forecasts.utils.unique.get, editable=False, max_length=50, unique=True)),
            ],
        ),
    ]
